name: CI/CD
on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master
  repository_dispatch:
    schedule:
      - cron: '5 12 * * 0'
jobs:
  CI-CD:
    runs-on: ubuntu-latest
    steps:
      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env.production
      - name: Check out repository code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install packages
        run: npm install
      - name: Build
        run: GATSBY_PRISMIC_REPO_NAME=$repoName PRISMIC_ACCESS_TOKEN=$prismicToken PRISMIC_CUSTOM_TYPES_API_TOKEN=$prismicTypesToken npm run build
      - name: Create CNAME
        run: |
          touch public/CNAME
          echo "juanmurillo.co" > public/CNAME
      - name: Deploy
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          git remote set-url origin https://${github_token}@github.com/${repository}
          npm run deploy
        env:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          repoName: ${{ secrets.GATSBY_PRISMIC_REPO_NAME }}
          prismicToken: ${{ secrets.PRISMIC_ACCESS_TOKEN }}
          prismicTypesToken: ${{ secrets.PRISMIC_CUSTOM_TYPES_API_TOKEN }}
